// scripts/gen_bab15_riba.cjs
const fs = require('fs');

const ribaQuestions = [
  {
    id: 'rb_1',
    question: 'Enam komoditas ribawi manakah yang secara sharih (tegas) disebutkan oleh Rasulullah SAW dalam hadits Ubadah bin Shamit RA?',
    options: [
      { id: 'a', text: 'Emas, perak, unta, kambing, kurma, dan air' },
      { id: 'b', text: 'Emas, perak, gandum halus (burr), gandum kasar (sya\'ir), kurma (tamr), dan garam (milh)' },
      { id: 'c', text: 'Emas, tembaga, beras, jagung, kurma, dan minyak zaitun' },
      { id: 'd', text: 'Uang dinar, dirham, tanah pekarangan, kurma ajwah, madu, dan cuka' },
      { id: 'e', text: 'Pakaian, senjata besi, gandum, anggur kering, susu, dan garam laut' },
    ],
    correctOptionId: 'b',
    explanation: 'Dalam hadits riwayat Imam Muslim dari Ubadah bin Shamit RA, enam komoditas ribawi yang disebutkan adalah: emas, perak, burr (gandum halus), sya\'ir (gandum kasar), tamr (kurma), dan milh (garam).',
    dalil: 'HR. Muslim no. 1587: "Emas dengan emas, perak dengan perak, gandum dengan gandum, jelai dengan jelai, kurma dengan kurma, garam dengan garam..."',
  },
  {
    id: 'rb_2',
    question: 'Jika seseorang menukarkan 10 gram perhiasan emas lama (kadar 24 karat namun model kuno) dengan 9 gram perhiasan emas baru (kadar 24 karat dengan model modern) secara tunai di tempat. Bagaimanakah hukum transaksi barter tersebut?',
    options: [
      { id: 'a', text: 'Halal karena selisih 1 gram merupakan kompensasi ongkos pembuatan perhiasan baru' },
      { id: 'b', text: 'Haram karena tergolong Riba Al-Fadhl akibat adanya kelebihan takaran/timbangan pada komoditas sejenis' },
      { id: 'c', text: 'Mubah selama kedua belah pihak saling ridha tanpa paksaan' },
      { id: 'd', text: 'Makruh tanzih tetapi jual belinya sah' },
      { id: 'e', text: 'Sah asalkan disertai bukti nota toko' },
    ],
    correctOptionId: 'b',
    explanation: 'Pertukaran barang ribawi yang satu jenis (emas dengan emas) wajib memenuhi dua syarat mutlak: mitslan bi mitslin (sama berat timbangannya) dan yadan bi yadin (tunai). Perbedaan kualitas/model tidak membolehkan selisih berat. Transaksi ini adalah Riba Fadhl.',
    dalil: 'HR. Bukhari no. 2175 & Muslim no. 1584: "Emas dengan emas sama timbangannya... barangsiapa menambah atau meminta tambahan maka ia telah berbuat riba."',
  },
  {
    id: 'rb_3',
    question: 'Bagaimanakah solusi syar\'i yang diajarkan oleh Rasulullah SAW kepada Bilal bin Rabah RA ketika Bilal ingin menukarkan kurma berkualitas rendah sebanyak dua sha\' dengan kurma berkualitas tinggi (kurma barni) sebanyak satu sha\'?',
    options: [
      { id: 'a', text: 'Boleh ditukar langsung asalkan disaksikan oleh dua orang saksi adil' },
      { id: 'b', text: 'Juallah kurma berkualitas rendah tersebut terlebih dahulu dengan uang dirham, kemudian belilah kurma berkualitas tinggi dengan uang dirham hasil penjualan tersebut' },
      { id: 'c', text: 'Campurkan kedua kurma tersebut agar menjadi kualitas rata-rata' },
      { id: 'd', text: 'Sedekahkan separuh kurma sebelum melakukan barter' },
      { id: 'e', text: 'Tambahkan buah anggur sebagai pelengkap barter' },
    ],
    correctOptionId: 'b',
    explanation: 'Rasulullah SAW bersabda: "Awwah! \'Ainur ribā! Jangan engkau lakukan itu! Tetapi juallah kurma yang rendah mutunya dengan uang (dirham), lalu belilah kurma yang bagus dengan uang tersebut."',
    dalil: 'HR. Bukhari no. 2201 & Muslim no. 1593 dari Abu Sa\'id Al-Khudri RA.',
  },
  {
    id: 'rb_4',
    question: 'Dua orang pedagang melakukan transaksi penukaran 100 gram emas batangan dengan 1.000 gram perak batangan. Kuantitas timbangannya berbeda dan penyerahan perak ditangguhkan selama 3 hari kerja. Mengapa transaksi ini dinyatakan HARAM?',
    options: [
      { id: 'a', text: 'Karena emas dan perak tidak boleh diperjualbelikan antar sesama pedagang' },
      { id: 'b', text: 'Karena pertukaran komoditas ribawi yang berlainan jenis namun satu \'illat (tsamaniyyah/alat tukar) wajib diserahterimakan secara tunai seketika (yadan bi yadin) di majelis akad' },
      { id: 'c', text: 'Karena berat perak harus sama persis dengan berat emas (100 gram)' },
      { id: 'd', text: 'Karena nilai kurs perak lebih rendah daripada emas' },
      { id: 'e', text: 'Karena transaksi logam mulia wajib melibatkan perbankan syariah' },
    ],
    correctOptionId: 'b',
    explanation: 'Emas dan perak memiliki \'illat yang sama yaitu tsamaniyyah (alat tukar). Ketika jenisnya berlainan, diperbolehkan berbeda kuantitas (tafadhul), namun wajib diserahterimakan secara tunai di majelis akad (hulul/taqabudh). Menundanya adalah Riba Nasi\'ah.',
    dalil: 'HR. Muslim no. 1587: "Jika berlainan jenisnya, juallah sesuka kalian asalkan secara tunai dari tangan ke tangan."',
  },
  {
    id: 'rb_5',
    question: 'Ahmad meminjamkan uang tunai sebesar Rp 5.000.000 kepada Dani dengan syarat Dani wajib mengembalikannya sebesar Rp 5.500.000 pada bulan depan. Tambahan Rp 500.000 yang dipersyaratkan dalam hutang-piutang ini dinamakan:',
    options: [
      { id: 'a', text: 'Riba Al-Fadhl' },
      { id: 'b', text: 'Riba Al-Qardh' },
      { id: 'c', text: 'Riba Al-Yad' },
      { id: 'd', text: 'Riba As-Salam' },
      { id: 'e', text: 'Riba Al-Khafi' },
    ],
    correctOptionId: 'b',
    explanation: 'Riba Qardh adalah kelebihan atau manfaat yang dipersyaratkan oleh pemberi pinjaman kepada peminjam atas pokok hutang yang dipinjamkan.',
    dalil: 'Kaidah Fiqih: "Kullu qardhin jarra manfa\'atan fahuwa ribā" (Setiap utang-piutang yang menarik manfaat tambahan bagi kreditur adalah riba).',
  },
  {
    id: 'rb_6',
    question: 'Seseorang berhutang Rp 10.000.000 dengan jatuh tempo tanggal 1 Januari. Pada tanggal tersebut debitur belum sanggup membayar, lalu kreditur berkata: "Kamu mau bayar sekarang atau hutangmu bertambah menjadi Rp 12.000.000 dengan tempo mundur 2 bulan lagi?". Praktik pelipatgandaan hutang akibat tempo mundur ini adalah:',
    options: [
      { id: 'a', text: 'Riba Al-Jahiliyyah' },
      { id: 'b', text: 'Riba Al-Fadhl' },
      { id: 'c', text: 'Riba Al-Yad' },
      { id: 'd', text: 'Khiyar Syarat' },
      { id: 'e', text: 'Murabahah Lil Amir Bisy-Syira\'' },
    ],
    correctOptionId: 'a',
    explanation: 'Riba Jahiliyyah adalah penambahan beban hutang yang dikenakan kepada debitur karena keterlambatan melunasi hutang pada waktu jatuh tempo ("Imma an taqdhi wa imma an turbi").',
    dalil: 'QS. Ali \'Imran: 130: "Janganlah kamu memakan riba dengan berlipat ganda..."',
  },
  {
    id: 'rb_7',
    question: 'Dua orang melakukan barter antara 1 karung beras ketan dengan 1 karung beras pandanwangi. Akad disepakati tunai, namun pembeli pamit mengambil karung beras ketannya di rumah dan baru menyerahkannya 4 jam kemudian setelah majelis akad bubar. Riba jenis apakah yang terjadi?',
    options: [
      { id: 'a', text: 'Riba Al-Qardh' },
      { id: 'b', text: 'Riba Al-Yad' },
      { id: 'c', text: 'Riba Al-Jahiliyyah' },
      { id: 'd', text: 'Riba Al-Khafi' },
      { id: 'e', text: 'Bukan riba melainkan khiyar majlis' },
    ],
    correctOptionId: 'b',
    explanation: 'Riba Al-Yad terjadi ketika transaksi jual beli komoditas ribawi yang satu \'illat dilakukan tanpa serah terima seketika di majelis transaksi, di mana kedua pihak berpisah badan sebelum barang saling diserahterimakan.',
    dalil: 'HR. Bukhari no. 2134: "Menjual gandum dengan gandum adalah riba kecuali secara tunai dari tangan ke tangan (haa wa haa)."',
  },
  {
    id: 'rb_8',
    question: 'Apakah \'illat (alasan hukum) keharaman riba pada emas dan perak menurut pendapat mu\'tamad Mazhab Syafi\'i dan mayoritas fuqaha?',
    options: [
      { id: 'a', text: 'Karena emas dan perak ditambang dari dalam perut bumi' },
      { id: 'b', text: 'Ats-Tsamaniyyah (berfungsi mutlak sebagai standar nilai harga dan alat tukar/uang)' },
      { id: 'c', text: 'Karena warnanya yang berkilau dan disukai wanita' },
      { id: 'd', text: 'Karena berat jenisnya yang padat dan tahan karat' },
      { id: 'e', text: 'Karena jumlahnya yang terbatas di dunia' },
    ],
    correctOptionId: 'b',
    explanation: 'Menurut Mazhab Syafi\'i dan Maliki, \'illat ribawiyyah pada emas dan perak adalah Ghalabatuts Tsamaniyyah (sifat dasar sebagai pengukur nilai harga dan mata uang). Oleh karena itu uang kertas modern dianalogikan hukumnya persis dengan emas dan perak.',
    dalil: 'Kitab Al-Umm karya Imam Syafi\'i & Fiqih Sunnah.',
  },
  {
    id: 'rb_9',
    question: 'Mengapa mata uang fiat kertas modern (seperti Rupiah, Dolar, Ringgit, Real) dihukumi sama persis dengan emas dan perak dalam ketentuan hukum komoditas ribawi?',
    options: [
      { id: 'a', text: 'Karena uang kertas dicetak dengan tinta emas' },
      { id: 'b', text: 'Karena uang kertas memiliki \'illat tsamaniyyah, yaitu berfungsi penuh sebagai alat pembayaran dan pengukur nilai harga yang diakui secara sah' },
      { id: 'c', text: 'Karena uang kertas dapat ditukar dengan gandum di pasar' },
      { id: 'd', text: 'Karena undang-undang perbankan menetapkan demikian' },
      { id: 'e', text: 'Hanya berlaku jika ada jaminan emas fisik 100% di bank sentral' },
    ],
    correctOptionId: 'b',
    explanation: 'Keputusan Majma\' Al-Fiqh Al-Islami OKI No. 21 (9/3) menetapkan bahwa uang kertas adalah uang yang mandiri yang memiliki \'illat tsamaniyyah penuh sebagaimana dinar emas dan dirham perak, sehingga berlaku padanya seluruh hukum riba dan zakat.',
    dalil: 'Resolusi Majma\' Al-Fiqh Al-Islami (OKI) di Makkah & Fatwa DSN-MUI.',
  },
  {
    id: 'rb_10',
    question: 'Siapakah empat pihak yang secara tegas dilaknat oleh Rasulullah SAW dalam hadits shahih terkait transaksi riba?',
    options: [
      { id: 'a', text: 'Pemakan riba (pemberi kredit riba), penyetor riba (nasabah peminjam), pencatat transaksinya, dan dua orang saksinya' },
      { id: 'b', text: 'Pedagang pasar, pembeli barang, supir pengangkut, dan kuli panggul' },
      { id: 'c', text: 'Presiden direktur bank, kasir, satpam, dan cleaning service' },
      { id: 'd', text: 'Penggugat sengketa, hakim, panitera, dan saksi palsu' },
      { id: 'e', text: 'Penimbun barang, pemalsu timbangan, rentenir, dan pencuri' },
    ],
    correctOptionId: 'a',
    explanation: 'Rasulullah SAW melaknat pemakan riba (yang memungut keuntungan bunga), orang yang memberinya makan (debitur yang membayar bunga), penulis akta transaksi riba, serta kedua saksinya, dan beliau bersabda: "Mereka semua sama dosanya."',
    dalil: 'HR. Muslim no. 1598 dari Jabir bin Abdillah RA.',
  },
  {
    id: 'rb_11',
    question: 'Apakah ancaman dahsyat yang dinyatakan oleh Allah Ta\'ala dalam Surah Al-Baqarah ayat 279 bagi orang-orang yang tetap tidak mau meninggalkan sisa-sisa riba setelah datangnya larangan?',
    options: [
      { id: 'a', text: 'Akan dicabut hak warisnya di dunia' },
      { id: 'b', text: 'Pemberitahuan perang dari Allah dan Rasul-Nya (fa\'dzanū biharbin minallāhi wa rasūlih)' },
      { id: 'c', text: 'Kewajiban membayar denda emas seberat tubuhnya' },
      { id: 'd', text: 'Diasingkan dari kampung halaman selama 40 tahun' },
      { id: 'e', text: 'Dilarang masuk ke dalam pasar selamanya' },
    ],
    correctOptionId: 'b',
    explanation: 'Tidak ada dosa perbuatan maksiat yang diumumkan perang secara langsung oleh Allah dan Rasul-Nya di dalam Al-Qur\'an selain pelaku transaksi riba yang membangkang.',
    dalil: 'QS. Al-Baqarah: 279: "Maka jika kamu tidak mengerjakannya (meninggalkan riba), maka ketahuilah bahwa Allah dan Rasul-Nya akan memerangimu."',
  },
  {
    id: 'rb_12',
    question: 'Bagaimanakah kondisi orang-orang yang memakan harta riba saat dibangkitkan dari kuburnya pada hari kiamat kelak sebagaimana digambarkan dalam Al-Qur\'an?',
    options: [
      { id: 'a', text: 'Berjalan dengan wajah tertelungkup di atas tanah' },
      { id: 'b', text: 'Berdiri sempoyongan seperti orang yang kerasukan setan akibat penyakit gila (ka alladzī yatakhabbathuhusy-syaithānu minal mass)' },
      { id: 'c', text: 'Tidak memiliki lidah untuk berbicara' },
      { id: 'd', text: 'Tubuhnya dipenuhi luka lebam bernanah' },
      { id: 'e', text: 'Mata mereka buta dan telinga mereka tuli' },
    ],
    correctOptionId: 'b',
    explanation: 'Al-Qur\'an menggambarkan pemakan riba di hari kiamat dibangkitkan dalam keadaan sempoyongan, hilang kendali, dan seperti orang yang kerasukan setan lantaran kerakusan mereka memakan harta haram.',
    dalil: 'QS. Al-Baqarah: 275: "Orang-orang yang memakan riba tidak dapat berdiri melainkan seperti berdirinya orang yang kemasukan setan karena gila."',
  },
  {
    id: 'rb_13',
    question: 'Berdasarkan Keputusan Fatwa MUI No. 1 Tahun 2004 serta keputusan Lembaga Fiqih OKI, apakah status hukum sistem bunga (interest) yang diterapkan oleh perbankan konvensional dan lembaga keuangan ribawi?',
    options: [
      { id: 'a', text: 'Halal karena merupakan kompensasi biaya sewa uang yang wajar' },
      { id: 'b', text: 'Makruh bagi pengusaha besar dan mubah bagi rakyat miskin' },
      { id: 'c', text: 'HARAM MUTLAK karena memenuhi seluruh kriteria Riba An-Nasi\'ah dan Riba Al-Qardh' },
      { id: 'd', text: 'Subhat yang dimaafkan selama negara belum menerapkan syariat penuh' },
      { id: 'e', text: 'Halal jika bunganya di bawah tingkat inflasi tahunan' },
    ],
    correctOptionId: 'c',
    explanation: 'Fatwa MUI No. 1 Tahun 2004 secara tegas memutuskan bahwa praktik pembungaan uang oleh lembaga keuangan konvensional termasuk kategori Riba, dan hukumnya adalah HARAM, baik bagi nasabah perorangan maupun korporasi.',
    dalil: 'Fatwa MUI No. 1 Tahun 2004 tentang Bunga (Interest/Fa\'idah).',
  },
  {
    id: 'rb_14',
    question: 'Seseorang membeli sebuah laptop seharga Rp 12.000.000 dengan kredit cicilan selama 12 bulan (Rp 1.000.000/bulan) dari sebuah toko komputer. Jika ia membeli tunai harganya Rp 10.000.000. Saat akad di awal disepakati secara tegas bahwa ia memilih skema cicilan Rp 12.000.000 tanpa klausul bunga harian. Apakah transaksi kredit ini termasuk riba?',
    options: [
      { id: 'a', text: 'Riba karena harga kredit lebih mahal daripada harga tunai' },
      { id: 'b', text: 'Bukan riba, melainkan jual beli kredit cicilan (Bai\' Bithaman Ajil / Murabahah) yang sah menurut jumhur ulama karena adanya satu harga pasti yang disepakati saat akad' },
      { id: 'c', text: 'Riba Fadhl karena adanya selisih Rp 2.000.000' },
      { id: 'd', text: 'Haram karena mencakup dua akad dalam satu transaksi' },
      { id: 'e', text: 'Makruh tanzih dan wajib disedekahkan selisihnya' },
    ],
    correctOptionId: 'b',
    explanation: 'Jual beli barang dengan harga kredit yang lebih tinggi dari harga tunai diperbolehkan oleh mayoritas fuqaha (empat mazhab), asalkan kedua pihak menegaskan satu pilihan harga secara mengikat di majelis akad dan harga tersebut tidak bertambah jika terjadi keterlambatan.',
    dalil: 'Fatwa DSN-MUI No. 04/DSN-MUI/IV/2000 & Kitab Al-Mabsuth karya As-Sarkhasi.',
  },
  {
    id: 'rb_15',
    question: 'Sebuah aplikasi pinjaman online (pinjol) menetapkan biaya potongan administrasi di muka sebesar 20% dan denda keterlambatan harian 1% dari pokok pinjaman. Bagaimana status transaksi pinjaman tersebut?',
    options: [
      { id: 'a', text: 'Halal karena biaya administrasi adalah hak penyedia jasa platform digital' },
      { id: 'b', text: 'Riba ganda (murakkab) yang menghimpun Riba Qardh (potongan di muka) dan Riba Jahiliyyah (denda keterlambatan berbunga)' },
      { id: 'c', text: 'Mubah jika peminjam menandatangani persetujuan secara sadar' },
      { id: 'd', text: 'Sah sebagai akad Ijarah teknologi informasi' },
      { id: 'e', text: 'Hanya haram jika bunga melampaui 100%' },
    ],
    correctOptionId: 'b',
    explanation: 'Memotong dana pinjaman di muka sebagai imbalan keuntungan pinjaman serta mengenakan denda berbunga yang bertambah seiring berjalannya waktu adalah bentuk nyata perpaduan Riba Qardh dan Riba Jahiliyyah yang sangat zalim.',
    dalil: 'QS. Al-Baqarah: 278-279 & Fatwa MUI No. 1 Tahun 2004.',
  },
  {
    id: 'rb_16',
    question: 'Apakah hukum bagi seorang debitur yang melunasi hutangnya dengan menambahkan uang secara sukarela atas inisiatif sendiri tanpa adanya perjanjian atau syarat di awal akad?',
    options: [
      { id: 'a', text: 'Haram dan menjadi riba qardh' },
      { id: 'b', text: 'Sunnah dan sangat dianjurkan sebagai bentuk perbuatan ihsan dan akhlak mulia dalam melunasi hutang (Husnul Qadha\')' },
      { id: 'c', text: 'Makruh karena menimbulkan kecurigaan publik' },
      { id: 'd', text: 'Wajib ditolak oleh pihak yang meminjamkan' },
      { id: 'e', text: 'Uang kelebihan wajib diserahkan ke kas masjid desa' },
    ],
    correctOptionId: 'b',
    explanation: 'Memberikan tambahan atau hadiah saat melunasi hutang tanpa adanya syarat atau kebiasaan yang mengikat sebelumnya adalah sunnah yang dipraktikkan Nabi SAW. Beliau bersabda: "Sebaik-baik kalian adalah orang yang paling baik dalam melunasi hutangnya."',
    dalil: 'HR. Bukhari no. 2305 & Muslim no. 1601 dari Abu Hurairah RA.',
  },
  {
    id: 'rb_17',
    question: 'Jika seorang muslim memiliki tabungan di bank konvensional dan terlanjur mendapatkan bunga bank, bagaimanakah tindakan yang benar terhadap uang bunga tersebut?',
    options: [
      { id: 'a', text: 'Dimakan untuk kebutuhan konsumsi makanan keluarga sehari-hari' },
      { id: 'b', text: 'Disalurkan untuk kepentingan fasilitas umum kaum muslimin (seperti perbaikan jalan, jembatan, WC umum) tanpa mengharap pahala sedekah, melainkan sebagai proses pembersihan harta haram' },
      { id: 'c', text: 'Digunakan untuk membeli hewan qurban atau ongkos naik haji' },
      { id: 'd', text: 'Dibuang ke laut atau dibakar agar musnah' },
      { id: 'e', text: 'Dibiarkan mengendap di bank untuk menambah modal bank' },
    ],
    correctOptionId: 'b',
    explanation: 'Bunga bank adalah harta haram (mal haram lidzatih/kasb). Cara bertaubat dan melepaskannya bukan dengan memanfaatkannya untuk diri sendiri, melainkan menyalurkannya untuk kemaslahatan sarana publik atau fakir miskin sebagai dana kebajikan sosial (dana tathir).',
    dalil: 'Fatwa DSN-MUI tentang Pengelolaan Dana Sosial Keagamaan & Al-Majmu\' Imam Nawawi.',
  },
  {
    id: 'rb_18',
    question: 'Pertukaran mata uang Rupiah dengan Dolar Amerika Serikat (USD) secara tunai di konter pedagang valas (money changer) diperbolehkan dengan nilai kurs yang berbeda, dengan syarat mutlak:',
    options: [
      { id: 'a', text: 'Harus diserahkan dari tangan ke tangan (Taqābudh fil Majlis) sebelum kedua pihak berpisah' },
      { id: 'b', text: 'Nilai nominal uang kertas harus sama persis' },
      { id: 'c', text: 'Pembeli wajib memperlihatkan tiket pesawat ke Amerika' },
      { id: 'd', text: 'Uang Dolar boleh dikirimkan lewat paket pos 3 hari kemudian' },
      { id: 'e', text: 'Wajib menggunakan mata uang emas dinar sebagai perantara' },
    ],
    correctOptionId: 'a',
    explanation: 'Dalam transaksi valuta asing (Ash-Sharf), jika mata uang yang dipertukarkan berlainan negara/jenis, maka kursnya bebas mengikuti kesepakatan pasar, namun wajib diserahterimakan secara tunai dan seketika di tempat transaksi (hulul wa taqabudh).',
    dalil: 'Fatwa DSN-MUI No. 28/DSN-MUI/III/2002 tentang Jual Beli Mata Uang (Al-Sharf).',
  },
  {
    id: 'rb_19',
    question: 'Mengapa transaksi valas dengan sistem "Forward", "Futures", dan "Swap" yang melibatkan penyerahan mata uang berjangka di masa mendatang diharamkan dalam fiqih Islam?',
    options: [
      { id: 'a', text: 'Karena biaya komisi broker terlalu mahal' },
      { id: 'b', text: 'Karena melanggar syarat tunai (hulul dan taqabudh) dalam pertukaran mata uang ribawi serta mengandung unsur spekulasi judi (maysir) dan riba nasi\'ah' },
      { id: 'c', text: 'Karena mata uang asing adalah produk non-muslim' },
      { id: 'd', text: 'Karena transaksi dilakukan menggunakan jaringan internet' },
      { id: 'e', text: 'Karena nilai dolar selalu berubah setiap menit' },
    ],
    correctOptionId: 'b',
    explanation: 'Transaksi forward, futures, dan swap valas dilarang karena tidak memenuhi prinsip serah terima tunai seketika (yadan bi yadin) dalam jual beli mata uang ribawi, sehingga terjadi penundaan serah terima yang memicu Riba Nasi\'ah dan spekulasi gharar.',
    dalil: 'Fatwa DSN-MUI No. 28/DSN-MUI/III/2002 & Keputusan Akademi Fiqih Islam OKI.',
  },
  {
    id: 'rb_20',
    question: 'Dua orang petani menukar 50 kg beras rojolele dengan 50 kg beras c4. Mengapa barter ini sah menurut hukum syariat Islam?',
    options: [
      { id: 'a', text: 'Karena kedua beras tersebut memiliki rasa pulen yang sama' },
      { id: 'b', text: 'Karena memenuhi dua syarat utama pertukaran barang ribawi sejenis: timbangan sama persis (mitslan bi mitslin) dan diserahterimakan secara tunai (yadan bi yadin)' },
      { id: 'c', text: 'Karena harga pasarnya tidak melebihi satu juta rupiah' },
      { id: 'd', text: 'Karena petani dibebaskan dari hukum riba' },
      { id: 'e', text: 'Karena kedua beras tersebut sama-sama dipanen di pulau Jawa' },
    ],
    correctOptionId: 'b',
    explanation: 'Beras dengan beras adalah komoditas ribawi yang satu jenis (al-jins al-wahid). Syarat keabsahan pertukarannya adalah tamatsul (kesamaan takaran/timbangan) dan taqabudh (serah terima seketika di majelis transaksi).',
    dalil: 'HR. Muslim no. 1587 & Kitab Kifayatul Akhyar.',
  },
  {
    id: 'rb_21',
    question: 'Seorang rentenir memberikan pinjaman modal kepada pedagang kecil dengan perjanjian "Bunga 10% per bulan". Rentenir berdalih bahwa bisnis pedagang tersebut sangat untung besar sehingga pembagian bunga 10% adalah hal wajar. Bagaimanakah bantahan Al-Qur\'an terhadap dalih orang-orang yang menyamakan riba dengan perdagangan?',
    options: [
      { id: 'a', text: '"Dan janganlah kamu memakan harta di antara kamu dengan jalan batil"' },
      { id: 'b', text: '"Padahal Allah telah menghalalkan jual beli dan mengharamkan riba" (Wa ahallallāhul bai\'a wa harramar ribā)' },
      { id: 'c', text: '"Sesungguhnya orang-orang pemboros itu adalah saudara-saudara setan"' },
      { id: 'd', text: '"Dan mintalah pertolongan kepada Allah dengan sabar dan shalat"' },
      { id: 'e', text: '"Berlomba-lombalah kamu dalam kebaikan"' },
    ],
    correctOptionId: 'b',
    explanation: 'Kaum kafir dan pelaku riba beralasan bahwa "jual beli itu sama saja dengan riba" (Innamal bai\'u mitslur riba). Allah membantah keras anggapan tersebut dengan menegaskan perbedaan hakikinya: jual beli dihalalkan sedangkan riba diharamkan.',
    dalil: 'QS. Al-Baqarah: 275: "Yang demikian itu karena mereka berkata bahwa jual beli sama dengan riba, padahal Allah telah menghalalkan jual beli dan mengharamkan riba."',
  },
  {
    id: 'rb_22',
    question: 'Dalam kartu kredit syariah (Syariah Card), lembaga keuangan syariah dilarang membebankan bunga pinjaman atas tagihan yang belum dibayar. Sebagai gantinya, akad yang digunakan untuk transaksi pembayaran tunai/belanja adalah:',
    options: [
      { id: 'a', text: 'Akad Riba Jahiliyyah' },
      { id: 'b', text: 'Kombinasi Akad Kafalah (penjaminan), Qardh (pinjaman dana), dan Ijarah (biaya jasa layanan membership)' },
      { id: 'c', text: 'Akad Mufawadhah' },
      { id: 'd', text: 'Akad Rahn Mutlaq' },
      { id: 'e', text: 'Akad Muzara\'ah' },
    ],
    correctOptionId: 'b',
    explanation: 'Kartu kredit syariah menggunakan multi-akad yang sah: Kafalah (bank menjamin pembayaran ke merchant), Qardh (bank memberikan talangan dana pelunasan), dan Ijarah (biaya jasa fasilitas keanggotaan kartu tanpa dikaitkan dengan persentase utang).',
    dalil: 'Fatwa DSN-MUI No. 54/DSN-MUI/X/2006 tentang Syariah Card.',
  },
  {
    id: 'rb_23',
    question: 'Seorang rentenir memberikan pinjaman sebesar Rp 1.000.000, namun ia mewajibkan peminjam membersihkan pekarangan rumahnya setiap sore selama masa hutang belum lunas. Apakah status pekerjaan pembersihan pekarangan ini?',
    options: [
      { id: 'a', text: 'Halal karena bentuk gotong royong tetangga' },
      { id: 'b', text: 'Riba Manfa\'at (Riba Qardh dalam bentuk jasa fisik gratis yang dipersyaratkan atas pinjaman)' },
      { id: 'c', text: 'Mubah jika peminjam diberi minum es teh' },
      { id: 'd', text: 'Sedekah tenaga yang berpahala bagi peminjam' },
      { id: 'e', text: 'Akad ijarah mandiri yang terpisah' },
    ],
    correctOptionId: 'b',
    explanation: 'Manfaat yang dipersyaratkan dalam hutang tidak hanya berupa uang tunai, tetapi juga berupa jasa tenaga, tumpangan kendaraan, atau fasilitas fisik. Semua ini termasuk Riba Qardh yang diharamkan.',
    dalil: 'HR. Bukhari dalam Adab Al-Mufrad & Kaidah Fiqih Al-Qardh.',
  },
  {
    id: 'rb_24',
    question: 'Apakah dampak negatif destruktif dari praktik transaksi riba terhadap perekonomian dan tatanan sosial masyarakat menurut penjelasan para ulama?',
    options: [
      { id: 'a', text: 'Menyebabkan deflasi harga barang tambang' },
      { id: 'b', text: 'Melahirkan jurang ketimpangan sosial, memicu krisis hutang berkepanjangan, mematikan sektor riil produktif, dan menimbulkan pemerasan si kaya atas si miskin' },
      { id: 'c', text: 'Meningkatkan cadangan devisa emas negara secara berlebihan' },
      { id: 'd', text: 'Membuat pasar tradisional menjadi terlalu ramai' },
      { id: 'e', text: 'Mendorong semua orang menjadi petani' },
    ],
    correctOptionId: 'b',
    explanation: 'Riba memindahkan kekayaan dari pihak yang lemah kepada pihak penumpuk modal tanpa adanya kompensasi riil, memicu gelembung ekonomi (bubble economy), inflasi, serta merusak sendi tolong-menolong.',
    dalil: 'Kitab Al-Amwal karya Abu \'Ubaid & Hujjatullah Al-Balighah karya Syah Waliyullah Ad-Dahlawi.',
  },
  {
    id: 'rb_25',
    question: 'Manakah di antara prinsip utama perbankan dan keuangan syariah berikut yang menjadi antitesis (solusi pengganti) mutlak dari sistem ribawi?',
    options: [
      { id: 'a', text: 'Prinsip spekulasi margin valuta asing berisiko tinggi' },
      { id: 'b', text: 'Prinsip bagi hasil (profit and loss sharing), keterkaitan erat dengan aset sektor riil yang halal, keadilan sosial, dan transparansi amanah' },
      { id: 'c', text: 'Prinsip penetapan bunga tetap berbunga harian' },
      { id: 'd', text: 'Prinsip memonopoli komoditas pangan pokok masyarakat' },
      { id: 'e', text: 'Prinsip membebaskan seluruh utang korporasi besar saja' },
    ],
    correctOptionId: 'b',
    explanation: 'Sistem ekonomi syariah menggantikan sistem bunga ribawi dengan kemitraan bagi untung-rugi riil (mudharabah/musyarakah), jual beli aset riil (murabahah/salam/istishna\'), serta akad kebajikan sosial (qardh hasan/zakat/wakaf).',
    dalil: 'QS. Al-Baqarah: 275 & Kaidah: "Al-Kharaju bidh-dhaman" (HR. Tirmidzi).',
  },
];

const content = `import { RibaQuizQuestion } from '../../types/riba';

export const RIBA_QUIZ: RibaQuizQuestion[] = ${JSON.stringify(ribaQuestions, null, 2)};
`;

fs.writeFileSync('src/data/quizzes/ribaQuizData.ts', content, 'utf8');
console.log('Successfully generated src/data/quizzes/ribaQuizData.ts with 25 questions');
