// scripts/gen_bab14_hibah_wakaf.cjs
const fs = require('fs');

const hibahWakafQuestions = [
  {
    id: 'hw_1',
    question: 'Apakah perbedaan mendasar antara hibah, sedekah, dan hadiah dalam terminologi syariat Islam?',
    options: [
      { id: 'a', text: 'Hibah hanya untuk orang fakir, sedekah untuk sanak keluarga, dan hadiah untuk pejabat pemerintah' },
      { id: 'b', text: 'Sedekah bertujuan ibadah mendekatkan diri kepada Allah bagi yang membutuhkan, hadiah untuk memuliakan seseorang atau tanda kasih sayang, dan hibah adalah pemberian sukarela secara umum' },
      { id: 'c', text: 'Hibah wajib dikembalikan setelah satu tahun, sedangkan sedekah dan hadiah menjadi milik mutlak' },
      { id: 'd', text: 'Hadiah harus berupa uang tunai, sedekah berupa makanan, dan hibah berupa tanah atau properti' },
      { id: 'e', text: 'Ketiganya tidak memiliki perbedaan hukum dan wajib diijab-qabulkan di depan pengadilan agama' },
    ],
    correctOptionId: 'b',
    explanation: 'Dalam fiqih Islam: Shadaqah adalah pemberian karena mengharap pahala akhirat kepada orang yang membutuhkan; Hadiah adalah pemberian untuk memuliakan (ikram) atau mempererat cinta kasih; sedangkan Hibah adalah pemberian sukarela atas suatu harta tanpa mengharap imbalan materi secara umum.',
    dalil: 'Kitab Al-Mu\'tamad fil Fiqh Asy-Syafi\'i Jilid 3 & HR. Bukhari: "Saling memberilah hadiah, niscaya kalian saling mencintai."',
  },
  {
    id: 'hw_2',
    question: 'Seorang ayah menghibahkan sebuah rumah kepada salah seorang anak kandungnya, namun anak-anak yang lain sama sekali tidak diberikan bagian. Nabi SAW menolak menjadi saksi atas pemberian tersebut dan bersabda: "Bertakwalah kepada Allah dan bersikap adillah di antara anak-anakmu". Siapakah sahabat yang mengalami peristiwa ini?',
    options: [
      { id: 'a', text: 'Usamah bin Zaid RA' },
      { id: 'b', text: 'An-Nu\'man bin Basyir RA' },
      { id: 'c', text: 'Abdullah bin Umar RA' },
      { id: 'd', text: 'Jabir bin Abdillah RA' },
      { id: 'e', text: 'Sa\'ad bin Abi Waqqash RA' },
    ],
    correctOptionId: 'b',
    explanation: 'Kisah masyhur ini terjadi pada Basyir bin Sa\'ad yang hendak menghibahkan seorang budak kepada putranya, An-Nu\'man bin Basyir, namun istrinya meminta Rasulullah SAW bersaksi. Rasulullah menolak dan memerintahkan keadilan di antara semua anak.',
    dalil: 'HR. Bukhari no. 2587 & Muslim no. 1623 dari An-Nu\'man bin Basyir RA.',
  },
  {
    id: 'hw_3',
    question: 'Bagaimanakah hukum seseorang yang menarik kembali barang yang telah dihibahkan dan diserahterimakan kepada orang lain?',
    options: [
      { id: 'a', text: 'Boleh kapan saja selama pihak penerima belum menjual barang tersebut' },
      { id: 'b', text: 'Makruh tanzih jika penerima adalah orang yang tidak mampu' },
      { id: 'c', text: 'Haram mutlak dan diumpamakan seperti anjing yang menjilat kembali muntahannya, KECUALI hibah dari orang tua kepada anak kandungnya' },
      { id: 'd', text: 'Mubah dengan syarat membayar uang tebusan 50% dari harga barang' },
      { id: 'e', text: 'Sah secara perdata jika disetujui oleh saksi akad' },
    ],
    correctOptionId: 'c',
    explanation: 'Menarik kembali hibah yang sudah diserahkan hukumnya haram, diibaratkan seperti anjing yang menelan kembali muntahannya. Pengecualian satu-satunya diberikan kepada orang tua (ayah/ibu/kakek) yang menarik kembali hibah yang diberikan kepada anak kandungnya.',
    dalil: 'HR. Bukhari no. 2589 & Abu Dawud no. 3539: "Tidak halal bagi seseorang memberikan suatu pemberian lalu menariknya kembali, kecuali orang tua terhadap apa yang ia berikan kepada anaknya."',
  },
  {
    id: 'hw_4',
    question: 'Kapan kepemilikan barang hibah mengikat secara sempurna (lazim) menurut ketetapan Mazhab Syafi\'i?',
    options: [
      { id: 'a', text: 'Seketika saat lafal ijab diucapkan meskipun barang belum diserahkan' },
      { id: 'b', text: 'Setelah terjadinya serah terima fisik secara nyata (Al-Qabdh) dengan seizin pemberi hibah' },
      { id: 'c', text: 'Setelah berlalu waktu satu tahun hijriyah (haul)' },
      { id: 'd', text: 'Setelah penerima hibah membayar zakat barang tersebut' },
      { id: 'e', text: 'Setelah dicatatkan dalam akta notaris resmi' },
    ],
    correctOptionId: 'b',
    explanation: 'Dalam Mazhab Syafi\'i, akad hibah belum bersifat mengikat (lazim) hanya dengan ijab qabul. Kepemilikan baru berpindah dan mengikat secara sempurna setelah adanya serah terima fisik (Al-Qabdh) dengan izin wahib.',
    dalil: 'Kitab Matan Al-Ghayah wat Taqrib karya Qadhi Abu Syuja\', Fashl Al-Hibah.',
  },
  {
    id: 'hw_5',
    question: 'Seseorang yang menderita sakit parah yang membawanya kepada kematian (maradhul maut) menghibahkan seluruh hartanya kepada salah satu kerabatnya. Bagaimanakah tinjauan fiqih terhadap keabsahan hibah tersebut?',
    options: [
      { id: 'a', text: 'Sah 100% karena hibah adalah hak prerogatif mutlak pemilik harta semasa hidup' },
      { id: 'b', text: 'Hukum hibahnya disamakan dengan hukum wasiat: hanya berlaku maksimal sepertiga (1/3) dari total harta dan tidak berlaku bagi ahli waris kecuali disetujui ahli waris lainnya' },
      { id: 'c', text: 'Batal demi hukum dan seluruh hartanya langsung disita oleh baitul mal' },
      { id: 'd', text: 'Berlaku 50% dari harta tanpa memandang status ahli waris' },
      { id: 'e', text: 'Wajib ditangguhkan hingga 10 tahun setelah kematiannya' },
    ],
    correctOptionId: 'b',
    explanation: 'Tindakan tasharruf tabarru\' (hibah/sedekah) pada saat maradhul maut (sakit menjelang ajal) dibatasi oleh syariat setara dengan wasiat demi melindungi hak ahli waris, yaitu maksimal sepertiga harta bersih dan tidak sah bagi ahli waris tanpa kerelaan ahli waris lain.',
    dalil: 'HR. Muslim no. 1620 & Kaidah Ushul Fiqih.',
  },
  {
    id: 'hw_6',
    question: 'Apakah substansi utama dari ibadah Wakaf yang membedakannya secara mendasar dari hibah biasa?',
    options: [
      { id: 'a', text: 'Wakaf boleh ditarik kembali sewaktu-waktu jika wakif membutuhkan modal' },
      { id: 'b', text: 'Menahan pokok benda (tahsibul ashl) agar tidak dijual, diwariskan, atau dihibahkan, serta mengalirkan manfaatnya secara abadi untuk kebajikan fi sabilillah' },
      { id: 'c', text: 'Wakaf hanya sah jika penerimanya adalah fakir miskin yang beragama Islam' },
      { id: 'd', text: 'Penerima wakaf berhak memperjualbelikan tanah wakaf untuk membeli mobil' },
      { id: 'e', text: 'Wakaf harus diperbarui ikrarnya setiap 5 tahun sekali di hadapan bupati' },
    ],
    correctOptionId: 'b',
    explanation: 'Definisi syar\'i wakaf adalah menahan pokok harta (habsul ashl) dari segala bentuk pengalihan hak milik komersial (jual beli, waris, hibah) dan menyalurkan hasil atau manfaatnya (tasbilul manfa\'ah) di jalan Allah.',
    dalil: 'HR. Bukhari no. 2772 & Muslim no. 1633 (Hadits Wakaf Umar bin Khattab atas tanah Khaibar).',
  },
  {
    id: 'hw_7',
    question: 'Ketika Umar bin Khattab radhiyallahu \'anhu memperoleh sebidang tanah subur di Khaibar, beliau meminta petunjuk kepada Rasulullah SAW tentang cara terbaik menginfakkannya. Apakah nasihat Rasulullah SAW kepada beliau?',
    options: [
      { id: 'a', text: '"Juallah tanah itu lalu bagikan seluruh uangnya kepada fakir miskin Madinah"' },
      { id: 'b', text: '"Tahanlah pokok tanahnya dan sedekahkanlah hasil panen atau manfaatnya"' },
      { id: 'c', text: '"Bagikan tanah itu sebagai warisan kepada anak cucumu yang terlilit hutang"' },
      { id: 'd', text: '"Tukarkan tanah itu dengan 100 ekor unta perang"' },
      { id: 'e', text: '"Bangunlah benteng pertahanan militer di atasnya"' },
    ],
    correctOptionId: 'b',
    explanation: 'Rasulullah SAW bersabda kepada Umar: "In syi\'ta habasta ashlaha wa tashaddaqta biha" (Jika engkau mau, tahanlah pokoknya dan sedekahkanlah hasilnya). Umar lalu mewakafkannya dengan syarat tidak boleh dijual, dihibahkan, atau diwariskan.',
    dalil: 'HR. Bukhari no. 2772 & Muslim no. 1633.',
  },
  {
    id: 'hw_8',
    question: 'Manakah di antara syarat berikut yang merupakan syarat mutlak bagi benda yang diwakafkan (al-mauquf) menurut kesepakatan fuqaha?',
    options: [
      { id: 'a', text: 'Benda harus berupa makanan pokok yang siap dikonsumsi seketika' },
      { id: 'b', text: 'Benda harus memiliki sifat kekal zatnya (baqa\'ul ashl) dan manfaatnya dapat diambil secara berkelanjutan tanpa melenyapkan wujud fisiknya' },
      { id: 'c', text: 'Benda harus terbuat dari emas murni 24 karat' },
      { id: 'd', text: 'Benda harus dibeli dari pedagang di tanah suci Makkah' },
      { id: 'e', text: 'Benda harus bernilai minimal di atas 100 juta rupiah' },
    ],
    correctOptionId: 'b',
    explanation: 'Syarat barang wakaf adalah barang yang memiliki ketahanan materi fisik (baqa\'ul ashl) sehingga dapat dimanfaatkan secara berulang dan lestari. Benda yang langsung habis sekali pakai (seperti makanan dan minuman) tidak sah diwakafkan dalam bentuk wakaf benda.',
    dalil: 'Kitab Fathul Qarib Al-Mujib & Nihayatul Muhtaj.',
  },
  {
    id: 'hw_9',
    question: 'Apakah hukum mewakafkan benda yang langsung habis zatnya dalam satu kali penggunaan, seperti sekeranjang roti, sepiring nasi, atau sebotol minyak goreng untuk dikonsumsi?',
    options: [
      { id: 'a', text: 'Sah sebagai wakaf benda abadi' },
      { id: 'b', text: 'Tidak sah sebagai wakaf karena tidak terpenuhi syarat ketahanan pokok benda (baqa\'ul ashl), melainkan terhitung sebagai sedekah konsumtif biasa' },
      { id: 'c', text: 'Sah asalkan diniatkan wakaf selama 1 minggu' },
      { id: 'd', text: 'Makruh tanzih namun sah di mata hukum' },
      { id: 'e', text: 'Wajib diganti dengan uang tunai oleh nazhir' },
    ],
    correctOptionId: 'b',
    explanation: 'Benda yang lenyap zatnya saat dimanfaatkan tidak dapat diwakafkan menurut syarat wakaf klasik, karena konsep wakaf bertumpu pada keabadian pokok aset. Pemberian makanan dihukumi sebagai shadaqah biasa (ath\'imah).',
    dalil: 'Kitab Al-Majmu\' Syarah Al-Muhadzdzab karya Imam An-Nawawi, Jilid 15.',
  },
  {
    id: 'hw_10',
    question: 'Pak Harun mewakafkan sebidang kebun kelapa sawit seluas 5 hektar untuk membiayai operasional sebuah pondok pesantren. Siapakah yang secara hukum syariat dan perundang-undangan berkewajiban mengelola, menjaga keutuhan aset, dan menyalurkan hasil manfaat kebun tersebut?',
    options: [
      { id: 'a', text: 'Al-Waqif (orang yang berwakaf)' },
      { id: 'b', text: 'An-Nazhir (pengelola amanah wakaf)' },
      { id: 'c', text: 'Al-Mauquf \'Alaih (santri penerima manfaat)' },
      { id: 'd', text: 'Camat setempat selaku pejabat akta tanah' },
      { id: 'e', text: 'Ahli waris dari pihak ibu wakif' },
    ],
    correctOptionId: 'b',
    explanation: 'Nazhir adalah pihak perorangan, organisasi, atau badan hukum yang diberi amanah untuk mengelola, mengembangkan, dan memelihara harta benda wakaf sesuai dengan peruntukan yang diikrarkan oleh wakif.',
    dalil: 'UU No. 41 Tahun 2004 tentang Wakaf & Kitab Al-Hawi Al-Kabir karya Al-Mawardi.',
  },
  {
    id: 'hw_11',
    question: 'Berapakah batas maksimal hak imbalan/keuntungan yang boleh diterima oleh seorang Nazhir dari hasil bersih pengelolaan aset wakaf produktif menurut regulasi fikih dan UU Wakaf di Indonesia?',
    options: [
      { id: 'a', text: 'Maksimal 50% dari hasil panen kotor' },
      { id: 'b', text: 'Maksimal 10% dari hasil bersih pengelolaan harta benda wakaf' },
      { id: 'c', text: 'Nazhir dilarang menerima imbalan sepeser pun secara mutlak' },
      { id: 'd', text: 'Maksimal 25% dari nilai aset pokok wakaf' },
      { id: 'e', text: 'Sebesar upah minimum regional (UMR) tanpa batas persentase' },
    ],
    correctOptionId: 'b',
    explanation: 'Berdasarkan fiqih Islam dan Pasal 12 UU No. 41 Tahun 2004 tentang Wakaf, Nazhir berhak menerima imbalan dari hasil bersih pengelolaan dan pengembangan harta benda wakaf paling banyak 10% (sepuluh persen).',
    dalil: 'UU RI No. 41 Tahun 2004 Pasal 12 & Atsar Umar bin Khattab tentang hak nazhir makan secara ma\'ruf.',
  },
  {
    id: 'hw_12',
    question: 'Dalam fatwa Majelis Ulama Indonesia (MUI) tahun 2002 dan regulasi BWI, bagaimanakah status hukum "Wakaf Uang" (Cash Waqf)?',
    options: [
      { id: 'a', text: 'Haram karena lembaran uang kertas dapat robek dan mengalami inflasi' },
      { id: 'b', text: 'Boleh (jawaz) secara syar\'i karena nilai uang (qimah) dapat diputar dalam investasi produktif syariah yang pokoknya tetap terjaga dan labanya disalurkan' },
      { id: 'c', text: 'Hanya sah jika uangnya berupa koin dirham perak murni zaman Khulafaur Rasyidin' },
      { id: 'd', text: 'Makruh dan harus dikonversi menjadi tanah kuburan dalam 3 hari' },
      { id: 'e', text: 'Batal karena uang tidak termasuk benda tak bergerak' },
    ],
    correctOptionId: 'b',
    explanation: 'Fatwa Komisi Fatwa MUI (11 Mei 2002) menetapkan bahwa Wakaf Uang (Waqf Al-Nuqud) hukumnya jawaz (boleh), dengan syarat nilai pokok wakaf harus dijamin kelestariannya dan tidak boleh dialihkan/berkurang, sedangkan keuntungannya disalurkan untuk mauquf alaih.',
    dalil: 'Fatwa MUI tentang Wakaf Uang (2002) & Pendapat Imam Az-Zuhri dalam Shahih Bukhari.',
  },
  {
    id: 'hw_13',
    question: 'Sebuah masjid wakaf di tepi sungai terancam runtuh akibat abrasi banjir bandang yang parah. Pengurus berencana memindahkan lokasi masjid tersebut ke tempat yang lebih aman dengan cara menjual tanah lama yang terancam runtuh dan membeli tanah baru yang lebih luas. Tindakan penukaran atau penggantian harta benda wakaf ini dalam fiqih disebut:',
    options: [
      { id: 'a', text: 'Al-Ijarah' },
      { id: 'b', text: 'Al-Istibdal (atau Ta\'widh Al-Waqf)' },
      { id: 'c', text: 'Al-Ghashab' },
      { id: 'd', text: 'Al-Iqtha\'' },
      { id: 'e', text: 'Al-Hima' },
    ],
    correctOptionId: 'b',
    explanation: 'Istibdal Al-Waqf adalah tindakan menjual atau menukar suatu aset wakaf yang rusak/tidak berfungsi lagi untuk digantikan dengan aset lain yang sepadan atau lebih baik demi menjaga kesinambungan tujuan wakaf. Mazhab Hanafi dan Hanbali membolehkannya jika ada maslahat dharuriyyah.',
    dalil: 'Kitab Al-Mughni karya Ibnu Qudamah & Majallatul Ahkam Al-\'Adliyyah pasal 1845.',
  },
  {
    id: 'hw_14',
    question: 'Seorang kakek mewakafkan rumah besarnya dengan ikrar: "Rumah ini saya wakafkan khusus untuk tempat tinggal anak cucu keturunan saya yang miskin, dan jika keturunan saya punah baru diserahkan kepada fakir miskin umum". Model wakaf keluarga ini diistilahkan sebagai:',
    options: [
      { id: 'a', text: 'Waqaf Khairi' },
      { id: 'b', text: 'Waqaf Ahli (atau Waqaf Dzurri)' },
      { id: 'c', text: 'Waqaf Musytarak' },
      { id: 'd', text: 'Waqaf Sanawi' },
      { id: 'e', text: 'Waqaf Mu\'aqqat' },
    ],
    correctOptionId: 'b',
    explanation: 'Waqaf Ahli (atau Waqaf Dzurri) adalah wakaf yang diperuntukkan secara khusus bagi kemaslahatan keluarga, kerabat, atau anak cucu keturunan wakif sendiri demi mencegah mereka jatuh miskin.',
    dalil: 'HR. Bukhari no. 2769 (Kisah Abu Thalhah mewakafkan kebun Bairuha untuk kerabatnya).',
  },
  {
    id: 'hw_15',
    question: 'Berbeda dengan Waqaf Ahli, wakaf yang sejak awal diikrarkan untuk kepentingan umum umat, seperti pembangunan rumah sakit, jembatan, madrasah, dan sumur air bersih untuk seluruh kaum muslimin, dinamakan:',
    options: [
      { id: 'a', text: 'Waqaf Khairi' },
      { id: 'b', text: 'Waqaf Ahli' },
      { id: 'c', text: 'Waqaf Dzurri' },
      { id: 'd', text: 'Waqaf Fardi' },
      { id: 'e', text: 'Waqaf Muqayyad' },
    ],
    correctOptionId: 'a',
    explanation: 'Waqaf Khairi adalah wakaf yang manfaatnya dialokasikan langsung untuk kemaslahatan umum (kebajikan publik) tanpa dibatasi pada garis kekerabatan tertentu.',
    dalil: 'Kitab Al-Fiqh Al-Islami wa Adillatuhu Jilid 10.',
  },
  {
    id: 'hw_16',
    question: 'Utsman bin Affan radhiyallahu \'anhu membeli sebuah sumur milik seorang Yahudi di Madinah seharga 20.000 dirham, lalu mewakafkannya agar seluruh penduduk Madinah bebas mengambil air secara cuma-cuma tanpa dipungut biaya. Apakah nama sumur bersejarah tersebut?',
    options: [
      { id: 'a', text: 'Sumur Zamzam' },
      { id: 'b', text: 'Sumur Rumah (Bi\'ru Rumah)' },
      { id: 'c', text: 'Sumur Budha\'ah' },
      { id: 'd', text: 'Sumur Khaibar' },
      { id: 'e', text: 'Sumur Tabuk' },
    ],
    correctOptionId: 'b',
    explanation: 'Sumur Rumah (Bi\'ru Rumah) dibeli oleh Utsman bin Affan RA setelah Nabi SAW menjanjikan surga bagi siapa yang membelinya untuk diwakafkan bagi kaum muslimin. Aset wakaf ini masih produktif hingga era modern.',
    dalil: 'HR. Bukhari no. 2778 & Tirmidzi no. 3703.',
  },
  {
    id: 'hw_17',
    question: 'Manakah di antara berikut ini yang TIDAK termasuk ke dalam Rukun Wakaf yang wajib terpenuhi agar ikrar wakaf sah menurut jumhur fuqaha?',
    options: [
      { id: 'a', text: 'Al-Waqif (orang yang mewakafkan hartanya)' },
      { id: 'b', text: 'Al-Mauquf (benda atau aset yang diwakafkan)' },
      { id: 'c', text: 'Al-Mauquf \'Alaih (penerima peruntukan manfaat wakaf)' },
      { id: 'd', text: 'Shighat (ikrar atau lafal pernyataan wakaf)' },
      { id: 'e', text: 'Membayar uang retribusi perizinan kepada dinas perpajakan daerah' },
    ],
    correctOptionId: 'e',
    explanation: 'Empat rukun wakaf yang disepakati ulama adalah: 1. Al-Waqif, 2. Al-Mauquf, 3. Al-Mauquf \'Alaih, dan 4. Ash-Shighah (Ijab). Uang retribusi pajak bukan merupakan rukun syar\'i.',
    dalil: 'Kitab Matan Al-Ghayah wat Taqrib, Fashl Ahkam Al-Waqf.',
  },
  {
    id: 'hw_18',
    question: 'Seseorang berikrar wakaf dengan menyatakan: "Saya wakafkan gedung ini untuk sekolah yatim selama 5 tahun saja, dan setelah 5 tahun gedung ini kembali menjadi milik pribadi saya". Bagaimanakah keabsahan wakaf ini menurut pandangan Mazhab Syafi\'i?',
    options: [
      { id: 'a', text: 'Sah karena wakaf boleh dibatasi waktu sesuai kehendak pemilik' },
      { id: 'b', text: 'Tidak sah / Batal, karena syarat mutlak shighat wakaf menurut Mazhab Syafi\'i adalah Ta\'bid (bersifat kekal selamanya) dan tidak boleh berjangka waktu (mu\'aqqat)' },
      { id: 'c', text: 'Makruh tetapi gedung otomatis menjadi milik wakif selamanya' },
      { id: 'd', text: 'Sah dan berubah menjadi akad sewa menyewa komersial' },
      { id: 'e', text: 'Wajib disita pemerintah provinsi' },
    ],
    correctOptionId: 'b',
    explanation: 'Menurut Mazhab Syafi\'i, syarat sah ikrar wakaf adalah Ta\'bid (berlaku abadi untuk selamanya). Membatasi waktu wakaf (ta\'qit) membatalkan akad wakaf karena bertentangan dengan prinsip penahanan aset permanen (meskipun Mazhab Maliki membolehkan wakaf berjangka).',
    dalil: 'Kitab Tuhfatul Muhtaj fi Syarh Al-Minhaj karya Ibnu Hajar Al-Haitami.',
  },
  {
    id: 'hw_19',
    question: 'Seorang donatur memberikan bingkisan mewah senilai 100 juta rupiah kepada seorang pejabat publik yang sedang memproses lelang proyek pemerintah yang diikutinya. Apakah hukum syar\'i pemberian semacam ini?',
    options: [
      { id: 'a', text: 'Halal karena diniatkan sebagai hadiah silaturahmi yang dianjurkan sunnah' },
      { id: 'b', text: 'Haram mutlak karena tergolong "Hadaya Al-\'Ummal" (hadiah bagi pejabat) yang merupakan bentuk suap terselubung (Ghulul / Risywah)' },
      { id: 'c', text: 'Mubah jika pejabat tersebut membagikan sebagian hadiahnya ke panti asuhan' },
      { id: 'd', text: 'Makruh tanzih selama tidak ada kuitansi resmi' },
      { id: 'e', text: 'Sah sebagai akad hibah bersyarat' },
    ],
    correctOptionId: 'b',
    explanation: 'Rasulullah SAW secara tegas melarang pemberian hadiah kepada pejabat atau aparatur negara yang memiliki wewenang (*hadāyal \'ummāl ghulūl*), karena hal itu hakikatnya adalah penyuapan (risywah) yang merusak integritas dan keadilan.',
    dalil: 'HR. Ahmad no. 23604 & Abu Dawud: "Hadiah-hadiah bagi para pejabat adalah bentuk kecurangan (ghulul)."',
  },
  {
    id: 'hw_20',
    question: 'Jika seorang wakif mewakafkan sebidang tanah untuk masjid, namun dalam ikrarnya ia mensyaratkan bahwa ia sendiri dan keturunannya berhak dimakamkan di mihrab depan masjid. Bagaimanakah status syarat tersebut?',
    options: [
      { id: 'a', text: 'Syarat sah dan wajib ditaati oleh seluruh jamaah shalat' },
      { id: 'b', text: 'Syaratnya batil (gugur) karena bertentangan dengan kehormatan shalat di masjid, sedangkan akad wakaf tanah masjidnya tetap sah' },
      { id: 'c', text: 'Akad wakaf batal total dan tanah dikembalikan kepada ahli waris' },
      { id: 'd', text: 'Masjid harus dibongkar dan diganti menjadi pemakaman keluarga' },
      { id: 'e', text: 'Jamaah masjid wajib membayar kompensasi sewa kuburan' },
    ],
    correctOptionId: 'b',
    explanation: 'Kaidah fiqih menyatakan bahwa syarat yang bertentangan dengan syariat atau merusak fungsi ibadah menjadi batal (laghwu), namun akad tabarru\' wakafnya tetap sah menurut pendapat rajih fuqaha.',
    dalil: 'Kaidah Fiqih: "Kullu syarthin laysa fī kitābillāh fahuwa bāthil" (HR. Bukhari no. 2168).',
  },
  {
    id: 'hw_21',
    question: 'Pemberian hibah dari orang tua kepada anaknya dapat berupa pemberian hak pakai atau pemberian hak milik mutlak. Jika orang tua memberikan rumah kepada anak dengan lafal "Umra" (seumur hidupmu), bagaimanakah status kepemilikan rumah tersebut menurut sabda Nabi SAW?',
    options: [
      { id: 'a', text: 'Rumah wajib dikembalikan kepada orang tua begitu anak menikah' },
      { id: 'b', text: 'Menjadi hak milik penuh bagi anak tersebut dan diwariskan kepada ahli warisnya setelah ia meninggal dunia (syariat menggugurkan syarat kembali ke pemilik asal)' },
      { id: 'c', text: 'Rumah otomatis menjadi milik baitul mal setelah anak wafat' },
      { id: 'd', text: 'Haram ditempati oleh cucu' },
      { id: 'e', text: 'Akad umra dilarang dan batal sejak awal' },
    ],
    correctOptionId: 'b',
    explanation: 'Rasulullah SAW menetapkan bahwa pemberian dengan akad \'Umra (pemberian seumur hidup) menjadi milik penerima dan ahli warisnya secara permanen. Syarat pengembalian ke pemilik awal setelah penerima wafat dianggap gugur.',
    dalil: 'HR. Muslim no. 1625: "Peliharalah harta kalian dan janganlah menjadikannya \'umra, karena barangsiapa diberi \'umra maka harta itu menjadi miliknya dan ahli warisnya."',
  },
  {
    id: 'hw_22',
    question: 'Manakah hadits shahih yang menjadi dalil utama mengenai keberlanjutan pahala amal jariyah melalui sedekah wakaf bahkan setelah seseorang meninggal dunia?',
    options: [
      { id: 'a', text: '"Apabila anak Adam wafat, terputuslah seluruh amalnya kecuali tiga perkara: sedekah jariyah, ilmu yang bermanfaat, dan anak shalih yang mendoakannya"' },
      { id: 'b', text: '"Sesungguhnya setiap amal bergantung pada niatnya"' },
      { id: 'c', text: '"Tangan di atas lebih baik daripada tangan di bawah"' },
      { id: 'd', text: '"Orang yang menunjuk kepada kebaikan sama pahalanya dengan orang yang mengerjakannya"' },
      { id: 'e', text: '"Agama itu adalah nasihat"' },
    ],
    correctOptionId: 'a',
    explanation: 'Hadits riwayat Imam Muslim dari Abu Hurairah RA menjelaskan tiga amalan yang pahalanya terus mengalir abadi, di mana ulama sepakat bahwa "shadaqah jariyah" dalam hadits ini maksud utamanya adalah WAKAF.',
    dalil: 'HR. Muslim no. 1631 dari Abu Hurairah RA.',
  },
  {
    id: 'hw_23',
    question: 'Apakah hukum bagi seseorang yang menjual atau menggadaikan tanah yang telah berstatus tanah wakaf untuk kepentingan pribadinya?',
    options: [
      { id: 'a', text: 'Boleh jika sedang terdesak kebutuhan biaya pernikahan' },
      { id: 'b', text: 'Haram mutlak, transaksinya batal demi hukum syariat dan merupakan dosa besar perampasan hak Allah (Ghashab)' },
      { id: 'c', text: 'Makruh selama pembelinya bersedia mewakafkannya kembali kelak' },
      { id: 'd', text: 'Mubah jika disetujui oleh ketua RT setempat' },
      { id: 'e', text: 'Sah asalkan uangnya disedekahkan separuh' },
    ],
    correctOptionId: 'b',
    explanation: 'Barang wakaf telah keluar dari kepemilikan pribadi manusia dan menjadi milik Allah yang ditujukan untuk kemaslahatan mauquf alaih. Menjual, menggadaikan, atau mewariskannya adalah perbuatan haram dan batil.',
    dalil: 'HR. Bukhari no. 2772: "Lā yubā\'u ashluhā walā yūhabu walā yūratsu" (Tidak boleh dijual pokoknya, tidak boleh dihibahkan, dan tidak boleh diwariskan).',
  },
  {
    id: 'hw_24',
    question: 'Dalam konsep filantropi Islam kontemporer, sebuah rumah sakit wakaf menginvestasikan dana wakaf tunai pada perkebunan sawit berkelanjutan, dan 100% laba dividennya digunakan untuk menggratiskan biaya pengobatan pasien dhuafa. Model ini merupakan manifestasi dari:',
    options: [
      { id: 'a', text: 'Wakaf Konsumtif Statis' },
      { id: 'b', text: 'Wakaf Produktif (Productive Waqf)' },
      { id: 'c', text: 'Riba Nasi\'ah' },
      { id: 'd', text: 'Baitul Mal Darurat' },
      { id: 'e', text: 'Gharar Tabarru\'' },
    ],
    correctOptionId: 'b',
    explanation: 'Wakaf produktif adalah pengelolaan aset atau dana wakaf yang diinvestasikan dalam sektor bisnis atau usaha riil halal yang menghasilkan surplus keuntungan secara terus-menerus untuk mendanai kemaslahatan umat.',
    dalil: 'Standar Syariah BWI (Badan Wakaf Indonesia) & Fatwa MUI.',
  },
  {
    id: 'hw_25',
    question: 'Bagaimanakah hukum melafalkan ikrar shighat wakaf secara lisan atau tulisan yang jelas (sharih) bagi seorang wakif yang berakal dan mampu berbicara?',
    options: [
      { id: 'a', text: 'Sunnah biasa, cukup dengan niat batin tanpa kata-kata' },
      { id: 'b', text: 'Wajib (Rukun), karena wakaf adalah akad tabarru\' pelepasan hak milik yang membutuhkan kejelasan shighat (ucapan atau tulisan) agar sah secara syar\'i' },
      { id: 'c', text: 'Makruh jika diucapkan di hadapan umum' },
      { id: 'd', text: 'Hanya dianjurkan bagi pejabat kementerian agama' },
      { id: 'e', text: 'Boleh diganti dengan senyuman dan jabat tangan' },
    ],
    correctOptionId: 'b',
    explanation: 'Shighat (ikrar wakaf) adalah salah satu dari empat rukun pokok wakaf. Wakaf tidak sah hanya dengan niat di dalam hati tanpa adanya lafal sharih (tegas) atau kinayah (kiasan disertai niat) atau tulisan yang jelas.',
    dalil: 'Kitab Al-Majmu\' Syarah Al-Muhadzdzab Jilid 15 & Fiqih Sunnah.',
  },
];

const content = `import { HibahWakafQuizQuestion } from '../../types/hibahWakaf';

export const HIBAH_WAKAF_QUIZ: HibahWakafQuizQuestion[] = ${JSON.stringify(hibahWakafQuestions, null, 2)};
`;

fs.writeFileSync('src/data/quizzes/hibahWakafQuizData.ts', content, 'utf8');
console.log('Successfully generated src/data/quizzes/hibahWakafQuizData.ts with 25 questions');
