// scripts/gen_bab16_jinayat.cjs
const fs = require('fs');

const jinayatQuestions = [
  {
    id: 'jn_1',
    question: 'Seseorang dengan sengaja menusukkan sebilah pedang tajam tepat ke bagian dada musuhnya yang berakibat korban meninggal seketika di tempat. Kategori pembunuhan apakah tindak pidana tersebut dalam fiqih jinayat?',
    options: [
      { id: 'a', text: 'Pembunuhan Mirip Sengaja (Qatlu Syibh \'Amd)' },
      { id: 'b', text: 'Pembunuhan Sengaja Murni (Qatlu \'Amd)' },
      { id: 'c', text: 'Pembunuhan Tersalah (Qatlu Khatha\')' },
      { id: 'd', text: 'Pembunuhan Membela Diri Tanpa Pidana' },
      { id: 'e', text: 'Pembunuhan Syubhat Jarimah' },
    ],
    correctOptionId: 'b',
    explanation: 'Qatlu \'Amd (Pembunuhan Sengaja) terjadi ketika pelaku sengaja bermaksud membunuh korban dan menggunakan alat yang menurut kebiasaan umum pasti atau berpotensi besar mematikan (seperti senjata tajam atau senjata api). Hukuman pokoknya adalah Qishash.',
    dalil: 'QS. Al-Baqarah: 178: "Diwajibkan atas kamu qishash berkenaan dengan orang-orang yang dibunuh."',
  },
  {
    id: 'jn_2',
    question: 'Seorang guru memukul betis muridnya menggunakan sebatang penggaris kayu tipis dengan tujuan mendidik. Tanpa disangka, murid tersebut terjatuh, terbentur batu, dan meninggal dunia. Jenis pembunuhan apakah kasus ini dalam klasifikasi syariat?',
    options: [
      { id: 'a', text: 'Pembunuhan Sengaja (Qatlu \'Amd)' },
      { id: 'b', text: 'Pembunuhan Tersalah Murni (Qatlu Khatha\')' },
      { id: 'c', text: 'Pembunuhan Mirip Sengaja (Qatlu Syibh \'Amd)' },
      { id: 'd', text: 'Bukan pembunuhan melainkan takdir murni tanpa konsekuensi hukum' },
      { id: 'e', text: 'Tindak pidana hudud berencana' },
    ],
    correctOptionId: 'c',
    explanation: 'Qatlu Syibh \'Amd adalah pelaku sengaja melakukan penganiayaan ringan kepada korban, namun menggunakan alat yang menurut kebiasaan umum tidak mematikan (seperti lidi, penggaris, atau tangan kosong), yang ternyata mengakibatkan kematian.',
    dalil: 'HR. Abu Dawud no. 4547 & An-Nasa\'i no. 4791 tentang pembunuhan dengan cambuk atau tongkat.',
  },
  {
    id: 'jn_3',
    question: 'Seorang pemburu melepaskan tembakan senapan angin ke arah seekor burung di atas pohon, namun peluru meleset dan mengenai seorang pencari kayu yang tidak terlihat di balik semak hingga tewas. Kategori pembunuhan apakah peristiwa ini?',
    options: [
      { id: 'a', text: 'Pembunuhan Sengaja (Qatlu \'Amd)' },
      { id: 'b', text: 'Pembunuhan Mirip Sengaja (Qatlu Syibh \'Amd)' },
      { id: 'c', text: 'Pembunuhan Tersalah / Keliru (Qatlu Khatha\')' },
      { id: 'd', text: 'Pembunuhan Berencana' },
      { id: 'e', text: 'Tindak Pidana Ta\'zir Berat' },
    ],
    correctOptionId: 'c',
    explanation: 'Qatlu Khatha\' (Pembunuhan Tersalah) adalah kematian yang terjadi tanpa adanya niat perbuatan jahat sama sekali terhadap diri manusia (pelaku menembak hewan buruan atau sasaran sah, namun mengenai manusia secara tak sengaja).',
    dalil: 'QS. An-Nisa: 92: "Dan tidak layak bagi seorang mukmin membunuh seorang mukmin yang lain, kecuali karena tersalah (khatha\'an)."',
  },
  {
    id: 'jn_4',
    question: 'Dalam kasus pembunuhan sengaja murni (Qatlu \'Amd), bagaimanakah opsi pilihan hukum yang diberikan oleh syariat kepada para wali (ahli waris) korban?',
    options: [
      { id: 'a', text: 'Hanya boleh menuntut hukuman mati qishash tanpa pilihan lain' },
      { id: 'b', text: 'Memilih salah satu dari 3 opsi: menuntut Qishash (eksekusi mati), memaafkan dengan meminta Diyat Mughalladhah, atau memaafkan secara cuma-cuma tanpa kompensasi materi' },
      { id: 'c', text: 'Otomatis diampuni jika pelaku membayar denda ke kas negara' },
      { id: 'd', text: 'Pelaku wajib dijadikan budak abadi bagi keluarga korban' },
      { id: 'e', text: 'Wali korban tidak memiliki hak berbicara karena seluruhnya wewenang mutlak hakim' },
    ],
    correctOptionId: 'b',
    explanation: 'Dalam Qatlu \'Amd, hak darah ada di tangan wali korban: mereka berhak menuntut Qishash, atau berdamai dengan mengambil Diyat Mughalladhah tunai dari harta pelaku, atau memaafkan secara sukarela demi pahala akhirat.',
    dalil: 'QS. Al-Baqarah: 178 & HR. Bukhari no. 112: "Barangsiapa keluarganya dibunuh, maka ia memiliki dua pilihan terbaik: diyat atau qishash."',
  },
  {
    id: 'jn_5',
    question: 'Apakah hukuman kaffarah syar\'i yang diwajibkan atas pelaku pembunuhan tersalah (Qatlu Khatha\') di samping kewajiban membayar diyat kepada keluarga korban?',
    options: [
      { id: 'a', text: 'Memberi makan 60 orang miskin' },
      { id: 'b', text: 'Memerdekakan seorang budak mukmin, atau berpuasa selama 2 bulan berturut-turut (syahraini mutatabi\'aini) jika tidak mampu' },
      { id: 'c', text: 'Menunaikan ibadah haji sebanyak 3 kali' },
      { id: 'd', text: 'Membaca Al-Qur\'an 30 juz setiap malam' },
      { id: 'e', text: 'Menyembelih 10 ekor sapi jantan' },
    ],
    correctOptionId: 'b',
    explanation: 'Al-Qur\'an secara tegas menetapkan kaffarah pembunuhan tidak sengaja: memerdekakan budak beriman, dan bila tidak mendapatinya, maka wajib berpuasa dua bulan berturut-turut sebagai taubat kepada Allah.',
    dalil: 'QS. An-Nisa: 92: "...maka (wajib atasnya) memerdekakan seorang hamba sahaya yang beriman... barangsiapa tidak memperolehnya, maka hendaklah ia berpuasa dua bulan berturut-turut."',
  },
  {
    id: 'jn_6',
    question: 'Berapakah jumlah total unta yang wajib dibayarkan sebagai Diyat Jiwa Penuh (Diyat Kamilah) atas hilangnya nyawa seorang muslim merdeka?',
    options: [
      { id: 'a', text: '50 ekor unta' },
      { id: 'b', text: '100 ekor unta' },
      { id: 'c', text: '200 ekor unta' },
      { id: 'd', text: '1.000 ekor unta' },
      { id: 'e', text: '30 ekor unta' },
    ],
    correctOptionId: 'b',
    explanation: 'Ketetapan baku syariat yang diriwayatkan dari Rasulullah SAW menyatakan bahwa diyat pembunuhan seorang muslim merdeka adalah 100 ekor unta (atau senilai 1.000 dinar emas / 12.000 dirham perak).',
    dalil: 'HR. Abu Dawud no. 4541, At-Tirmidzi no. 1387, dan An-Nasa\'i no. 4801.',
  },
  {
    id: 'jn_7',
    question: 'Bagaimanakah komposisi rincian 100 ekor unta pada Diyat Mughalladhah (diyat berat) yang diterapkan pada kasus pembunuhan mirip sengaja atau pembunuhan sengaja yang dimaafkan?',
    options: [
      { id: 'a', text: '100 ekor unta jantan dewasa tanpa syarat kehamilan' },
      { id: 'b', text: '30 ekor Hiqqah (betina 3-4 tahun), 30 ekor Jadz\'ah (betina 4-5 tahun), dan 40 ekor Khalifah (unta betina yang sedang bunting)' },
      { id: 'c', text: 'Masing-masing 20 ekor dari lima tingkatan umur unta' },
      { id: 'd', text: '50 unta jantan dan 50 unta betina muda' },
      { id: 'e', text: '100 ekor unta bibit yang baru lahir' },
    ],
    correctOptionId: 'b',
    explanation: 'Diyat Mughalladhah diperberat dari segi kualitas unta: 30 hiqqah, 30 jadz\'ah, dan 40 khalifah (unta bunting). Ini mencerminkan tingkat keparahan jinayat.',
    dalil: 'HR. Abu Dawud no. 4547, At-Tirmidzi no. 1387, dan Ibnu Majah no. 2627.',
  },
  {
    id: 'jn_8',
    question: 'Siapakah pihak yang memikul kewajiban pembayaran Diyat pada kasus Pembunuhan Tersalah (Qatlu Khatha\') dan Pembunuhan Mirip Sengaja (Qatlu Syibh \'Amd)?',
    options: [
      { id: 'a', text: 'Dibayar 100% dari harta pribadi pelaku seketika dalam satu malam' },
      { id: 'b', text: 'Ditanggung bersama oleh \'Aqilah (kerabat laki-laki pihak ayah dari pelaku) dan diangsur selama 3 tahun' },
      { id: 'c', text: 'Dibayar oleh baitul mal negara tanpa melibatkan keluarga pelaku' },
      { id: 'd', text: 'Ditanggung oleh aparat kepolisian setempat' },
      { id: 'e', text: 'Dibagi rata antara keluarga korban dan keluarga pelaku' },
    ],
    correctOptionId: 'b',
    explanation: 'Dalam pembunuhan tidak sengaja dan mirip sengaja, beban diyat dipikul oleh \'Aqilah pelaku (keluarga patrilineal) sebagai bentuk solidaritas tolong-menolong (at-takaful al-ijtima\'i), dan pembayarannya dapat diangsur maksimal 3 tahun.',
    dalil: 'HR. Bukhari no. 6909 & Muslim no. 1681 tentang putusan Nabi SAW mengenai diyat wanita Bani Lihyan.',
  },
  {
    id: 'jn_9',
    question: 'Seorang ayah kandung dengan sengaja membunuh anak kandungnya sendiri. Apakah hukuman mati Qishash dapat dijatuhkan kepada sang ayah menurut pendapat jumhur fuqaha (termasuk Mazhab Syafi\'i)?',
    options: [
      { id: 'a', text: 'Wajib diqishash mati demi keadilan mutlak' },
      { id: 'b', text: 'Tidak dijatuhi hukuman qishash mati (berdasarkan hadits larangan qishash orang tua atas anak), namun ayah wajib membayar diyat mughalladhah dan dikenakan ta\'zir berat' },
      { id: 'c', text: 'Dibebaskan murni tanpa dosa karena ayah memiliki hak atas anaknya' },
      { id: 'd', text: 'Ayah diasingkan ke luar negeri selama 1 bulan' },
      { id: 'e', text: 'Ayah hanya wajib membaca istighfar 100 kali' },
    ],
    correctOptionId: 'b',
    explanation: 'Jumhur ulama berpendapat orang tua tidak diqishash karena membunuh anaknya berdasarkan sabda Nabi SAW: "Seorang ayah tidak diqishash karena membunuh anaknya". Sebagai gantinya, ia wajib membayar Diyat Mughalladhah dari harta pribadinya dan dihukum ta\'zir seberat-beratnya.',
    dalil: 'HR. Tirmidzi no. 1401, Ibnu Majah no. 2661, dan Ahmad no. 1/22.',
  },
  {
    id: 'jn_10',
    question: 'Pelaku tindak penganiayaan dengan sengaja memotong kedua tangan seorang korban hingga putus dari pergelangan tangan. Berapakah diyat anggota tubuh yang wajib dibayarkan pelaku jika tidak dilakukan qishash?',
    options: [
      { id: 'a', text: '1/4 diyat jiwa (25 ekor unta)' },
      { id: 'b', text: '1/2 diyat jiwa (50 ekor unta)' },
      { id: 'c', text: 'Satu Diyat Jiwa Penuh (100 ekor unta)' },
      { id: 'd', text: 'Dua diyat jiwa penuh (200 ekor unta)' },
      { id: 'e', text: 'Cukup meminta maaf di hadapan majelis' },
    ],
    correctOptionId: 'c',
    explanation: 'Kaidah fiqih menetapkan: organ tubuh yang berpasangan (seperti dua mata, dua telinga, dua tangan, dua kaki), jika dirusak salah satunya bernilai 1/2 diyat (50 unta), dan jika dirusak KEDUANYA maka bernilai SATU DIYAT PENUH (100 ekor unta).',
    dalil: 'Surat Rasulullah SAW kepada \'Amr bin Hazm (HR. Malik dalam Al-Muwaththa\' & An-Nasa\'i no. 4853).',
  },
  {
    id: 'jn_11',
    question: 'Jika seseorang menganiaya korban hingga merusak satu organ tunggal yang di dalam tubuh hanya ada satu-satunya (seperti memotong habis lidah atau hidung korban hingga kehilangan fungsi pengecap/penciuman), berapakah nilai diyatnya?',
    options: [
      { id: 'a', text: '10 ekor unta' },
      { id: 'b', text: '33 ekor unta' },
      { id: 'c', text: '50 ekor unta' },
      { id: 'd', text: 'Satu Diyat Jiwa Penuh (100 ekor unta)' },
      { id: 'e', text: '200 ekor unta' },
    ],
    correctOptionId: 'd',
    explanation: 'Setiap organ tunggal di dalam tubuh manusia yang tidak memiliki pasangan (seperti hidung, lidah, kemaluan laki-laki) jika dirusak atau dihilangkan fungsinya, bernilai Diyat Penuh (100 ekor unta).',
    dalil: 'Kitab Al-Amwal karya Abu \'Ubaid & Kitab Al-Umm karya Asy-Syafi\'i.',
  },
  {
    id: 'jn_12',
    question: 'Pelaku melukai kepala korban hingga merobek kulit dan daging sampai menampakkan tulang tengkorak kepala (Luka Al-Mūdhihah). Berapakah kadar diyat syar\'i untuk luka Al-Mūdhihah?',
    options: [
      { id: 'a', text: '1 ekor unta' },
      { id: 'b', text: '5 ekor unta' },
      { id: 'c', text: '15 ekor unta' },
      { id: 'd', text: '33 ekor unta' },
      { id: 'e', text: '50 ekor unta' },
    ],
    correctOptionId: 'b',
    explanation: 'Luka Mūdhihah (luka di kepala/wajah yang menampakkan putihnya tulang) telah ditentukan kadar diyatnya secara pasti oleh nash sabda Nabi SAW, yaitu sebesar 5 ekor unta.',
    dalil: 'HR. Abu Dawud no. 4566 & An-Nasa\'i no. 4850: "Pada luka mudhihah diyatnya adalah lima ekor unta."',
  },
  {
    id: 'jn_13',
    question: 'Pelaku menusuk perut korban dengan belati hingga tembus ke dalam rongga perut bagian dalam (Luka Al-Jā\'ifah). Berapakah kadar diyat luka Al-Jā\'ifah?',
    options: [
      { id: 'a', text: '10 ekor unta' },
      { id: 'b', text: '20 ekor unta' },
      { id: 'c', text: 'Sepertiga Diyat Penuh (33,3 ekor unta / Ats-Tsuluts)' },
      { id: 'd', text: 'Separuh Diyat Penuh (50 ekor unta)' },
      { id: 'e', text: 'Dua pertiga Diyat Penuh' },
    ],
    correctOptionId: 'c',
    explanation: 'Luka Ja\'ifah adalah luka tusukan yang tembus hingga ke dalam rongga dada atau rongga perut. Diyatnya ditetapkan sebesar 1/3 diyat penuh (33 1/3 ekor unta).',
    dalil: 'Kitab Sunan An-Nasa\'i no. 4853 & Hadits \'Amr bin Hazm RA: "Wa fil jā\'ifati tsulutsud-diyah."',
  },
  {
    id: 'jn_14',
    question: 'Pelaku memukul kepala korban hingga memecahkan tulang tengkorak dan lukanya mengenai selaput pembungkus otak (Luka Al-Ma\'mūmah atau Al-Āmmah). Berapakah kadar diyatnya?',
    options: [
      { id: 'a', text: '1/3 Diyat Jiwa Penuh' },
      { id: 'b', text: '1/2 Diyat Jiwa Penuh' },
      { id: 'c', text: '1/4 Diyat Jiwa Penuh' },
      { id: 'd', text: '10 ekor unta' },
      { id: 'e', text: '100 ekor unta' },
    ],
    correctOptionId: 'a',
    explanation: 'Luka Ma\'mumah (luka yang mengenai selaput otak/ummur ra\'si) memiliki kadar diyat sebesar 1/3 (sepertiga) dari diyat jiwa penuh.',
    dalil: 'Hadits \'Amr bin Hazm RA: "Wa fil ma\'mūmati tsulutsud-diyah."',
  },
  {
    id: 'jn_15',
    question: 'Jika seseorang melukai bagian tubuh korban yang jenis lukanya TIDAK memiliki ketentuan ukuran nominal pasti dalam nash Al-Qur\'an dan Hadits (luka non-m مقدر), bagaimana cara menentukan nilai ganti rugi diyatnya?',
    options: [
      { id: 'a', text: 'Korban tidak berhak mendapatkan ganti rugi sepeser pun' },
      { id: 'b', text: 'Ditetapkan melalui Hukūmatul \'Adl (kompensasi penaksiran oleh para ahli medis dan hakim yang adil)' },
      { id: 'c', text: 'Otomatis dihitung sebesar 50 ekor unta' },
      { id: 'd', text: 'Ditentukan dengan melempar undian dadu' },
      { id: 'e', text: 'Pelaku wajib memberikan seluruh harta kekayaannya' },
    ],
    correctOptionId: 'b',
    explanation: 'Untuk luka atau cedera yang tidak memiliki takaran nash baku (ghair muqaddar), syariat menetapkan kompensasi berupa Hukūmah (Hukūmatul \'Adl), yaitu penaksiran selisih nilai penurunan kondisi tubuh korban oleh pakar yang adil.',
    dalil: 'Kitab Al-Mughni karya Ibnu Qudamah & Matan Minhajut Thalibin.',
  },
  {
    id: 'jn_16',
    question: 'Seseorang menganiaya seorang wanita hamil hingga wanita tersebut mengalami keguguran dan janinnya keluar dalam kondisi mati. Apakah nama diyat khusus untuk janin tersebut dan berapa kadarnya?',
    options: [
      { id: 'a', text: 'Diyat Mukhaffafah sebesar 50 ekor unta' },
      { id: 'b', text: 'Ghurrah (senilai 1/20 diyat penuh / 5 ekor unta atau memerdekakan budak)' },
      { id: 'c', text: 'Hukuman qishash mati bagi pelaku' },
      { id: 'd', text: 'Tidak ada diyat karena janin belum lahir hidup' },
      { id: 'e', text: 'Diyat kamilah 100 ekor unta' },
    ],
    correctOptionId: 'b',
    explanation: 'Diyat janin yang gugur dalam keadaan mati akibat penganiayaan disebut Ghurrah, yang nilainya setara dengan 5 ekor unta (1/10 diyat ibu atau 1/20 diyat penuh laki-laki) atau memerdekakan seorang budak.',
    dalil: 'HR. Bukhari no. 6905 & Muslim no. 1681 dari Abu Hurairah RA.',
  },
  {
    id: 'jn_17',
    question: 'Apakah filosofi utama diterapkannya hukum Qishash sebagaimana yang ditegaskan langsung oleh Allah Ta\'ala dalam Surah Al-Baqarah ayat 179?',
    options: [
      { id: 'a', text: 'Untuk memuaskan rasa dendam keluarga korban' },
      { id: 'b', text: 'Sebagai jaminan kelangsungan hidup dan keselamatan umat manusia (wa lakum fil qishāshi hayātun)' },
      { id: 'c', text: 'Untuk mengurangi kepadatan populasi penduduk bumi' },
      { id: 'd', text: 'Sebagai sarana pemasukan kas keuangan negara' },
      { id: 'e', text: 'Sebagai ritual adat masyarakat padang pasir' },
    ],
    correctOptionId: 'b',
    explanation: 'Tujuan disyariatkannya qishash adalah mencegah pertumpahan darah lebih luas. Ketika calon pembunuh mengetahui ia pasti dieksekusi mati jika membunuh, ia akan mengurungkan niatnya, sehingga jiwa manusia terselamatkan.',
    dalil: 'QS. Al-Baqarah: 179: "Dan dalam qishash itu ada (jaminan) kehidupan bagimu, wahai orang-orang yang berakal, agar kamu bertakwa."',
  },
  {
    id: 'jn_18',
    question: 'Lima orang preman bersekongkol dan secara bersama-sama mengeroyok dan menikam seorang pria hingga tewas di tempat. Bagaimana keputusan hukum Umar bin Khattab radhiyallahu \'anhu dalam kasus pembunuhan massal terhadap satu korban ini?',
    options: [
      { id: 'a', text: 'Hanya orang yang menikam pertama kali yang dieksekusi mati' },
      { id: 'b', text: 'Kelima-limanya wajib dihukum mati qishash secara bersamaan karena mereka bersekutu dalam perbuatan tersebut' },
      { id: 'c', text: 'Semua pelaku dibebaskan dari qishash dan hanya membayar 1/5 diyat' },
      { id: 'd', text: 'Dipilih satu orang secara acak lewat undian' },
      { id: 'e', text: 'Dikenakan denda kurungan penjara 1 tahun saja' },
    ],
    correctOptionId: 'b',
    explanation: 'Khalifah Umar bin Khattab menetapkan bahwa sekelompok orang yang bersekongkol membunuh satu orang semuanya dihukum qishash mati. Beliau bersabda: "Seandainya seluruh penduduk Shan\'a bersekutu membunuhnya, niscaya aku bunuh mereka semua."',
    dalil: 'Atsar Shahih dalam Shahih Bukhari Bab Qisasul Jama\'ah bil Wahid.',
  },
  {
    id: 'jn_19',
    question: 'Manakah di antara syarat berikut yang menjadi syarat sah pelaksanaan hukum Qishash dalam pengadilan Islam?',
    options: [
      { id: 'a', text: 'Pelaku pembunuhan harus berjenis kelamin laki-laki saja' },
      { id: 'b', text: 'Pelaku mukallaf (baligh & berakal), korban darahnya terlindungi (ma\'shum ad-dam), dan ada kesetaraan derajat kesucian darah (tamatsul/kufu\')' },
      { id: 'c', text: 'Pembunuhan harus terjadi di wilayah tanah haram Makkah' },
      { id: 'd', text: 'Keluarga korban wajib membayar biaya eksekusi kepada algojo' },
      { id: 'e', text: 'Pelaku harus berstatus sebagai pegawai negeri' },
    ],
    correctOptionId: 'b',
    explanation: 'Syarat qishash meliputi: 1. Pelaku baligh dan berakal; 2. Korban darahnya terjaga (bukan kafir harbi atau murtad); 3. Pelaku bukan orang tua kandung korban; 4. Adanya kesetaraan status.',
    dalil: 'Kitab Matan Al-Ghayah wat Taqrib karya Qadhi Abu Syuja\'.',
  },
  {
    id: 'jn_20',
    question: 'Sebuah jasad manusia ditemukan terbunuh di sebuah pemukiman tertentu dengan luka tikaman, namun tidak ada bukti saksi mata maupun pengakuan pelaku. Untuk menyelesaikan sengketa darah ini, syariat menetapkan prosedur sumpah sebanyak 50 kali yang dikenal dengan istilah:',
    options: [
      { id: 'a', text: 'Li\'an' },
      { id: 'b', text: 'Al-Qasāmah' },
      { id: 'c', text: 'Zhihar' },
      { id: 'd', text: 'Ila\'' },
      { id: 'e', text: 'Tafwidz' },
    ],
    correctOptionId: 'b',
    explanation: 'Al-Qasāmah adalah pengucapan sumpah sebanyak 50 kali oleh 50 orang kerabat korban (atau diulang) untuk menuntut diyat atas mayat yang ditemukan di lokasi tertentu disertai indikasi kuat (lautsah).',
    dalil: 'HR. Bukhari no. 6898 & Muslim no. 1669 (Kisah Qasamah Khaibar).',
  },
  {
    id: 'jn_21',
    question: 'Berapakah diyat jiwa seorang wanita muslimah merdeka dibandingkan dengan diyat laki-laki muslim merdeka menurut ketetapan ijma\' para sahabat dan imam mazhab empat?',
    options: [
      { id: 'a', text: 'Sama persis (100 ekor unta)' },
      { id: 'b', text: 'Separuh dari diyat laki-laki (50 ekor unta)' },
      { id: 'c', text: 'Seperempat dari diyat laki-laki (25 ekor unta)' },
      { id: 'd', text: 'Dua kali lipat lebih banyak (200 ekor unta)' },
      { id: 'e', text: 'Tergantung tingkat pendidikan wanita tersebut' },
    ],
    correctOptionId: 'b',
    explanation: 'Ijma\' ulama dan empat mazhab menetapkan bahwa diyat jiwa wanita muslimah adalah separuh dari diyat laki-laki (50 ekor unta), meskipun dalam hukum qishash nyawa laki-laki tetap diqishash mati jika membunuh wanita.',
    dalil: 'HR. Baihaqi no. 8/95 & Kitab Al-Ijma\' karya Ibnu Al-Mundzir.',
  },
  {
    id: 'jn_22',
    question: 'Seseorang memasang jebakan kabel listrik beraliran tegangan tinggi di sekeliling kebunnya tanpa rambu peringatan, yang mengakibatkan seorang pencuri buah tersengat listrik hingga tewas seketika. Mengapa pemilik kebun dikenakan pidana jinayat?',
    options: [
      { id: 'a', text: 'Karena mencuri buah adalah perbuatan terpuji' },
      { id: 'b', text: 'Karena tindakan tersebut tergolong jinayat Tasabbub (menyebabkan kematian orang lain melalui perbuatan berbahaya yang dilarang)' },
      { id: 'c', text: 'Karena pemilik kebun bukan petugas PLN resmi' },
      { id: 'd', text: 'Karena kabel listrik dilarang dipasang di luar rumah' },
      { id: 'e', text: 'Pemilik kebun bebas dari segala tuntutan hukum' },
    ],
    correctOptionId: 'b',
    explanation: 'Dalam fiqih jinayat, pertanggungjawaban pidana dapat terjadi secara langsung (mubasyarah) atau melalui sebab (tasabbub). Memasang perangkap mematikan yang tidak proporsional membebankan pertanggungjawaban jinayat syibh amd atau khatha\'.',
    dalil: 'Kaidah Fiqih: "Idzā ijtama\'al mubāsyiru wat mutasabbibu ghullibal mubāsyir" & Al-Mabsuth.',
  },
  {
    id: 'jn_23',
    question: 'Apakah hukuman bagi orang yang membunuh orang lain untuk membela diri (Difā\' \'an An-Nafs) saat diserang perampok bersenjata yang berniat membunuhnya, setelah segala upaya peringatan dan melarikan diri tidak berhasil?',
    options: [
      { id: 'a', text: 'Wajib diqishash mati' },
      { id: 'b', text: 'Bebas dari hukuman qishash dan diyat, dan darah perampok tersebut berstatus hadar (sia-sia / halal ditumpahkan demi membela diri)' },
      { id: 'c', text: 'Wajib membayar separuh diyat' },
      { id: 'd', text: 'Wajib berpuasa kaffarah selama 1 tahun' },
      { id: 'e', text: 'Dikenakan kurungan seumur hidup' },
    ],
    correctOptionId: 'b',
    explanation: 'Membela jiwa, kehormatan, dan harta dari serangan zalim (Daf\'u Ash-Sha\'il) diperbolehkan dalam Islam. Jika penyerang mati dalam perlawanan proporsional membela diri, darahnya hadar (sia-sia) tanpa tuntutan qishash maupun diyat.',
    dalil: 'HR. Muslim no. 140: "Barangsiapa terbunuh karena membela hartanya maka ia syahid, dan darah penyerang di neraka."',
  },
  {
    id: 'jn_24',
    question: 'Bagaimanakah ketentuan hukum jika seorang anak kecil (belum baligh) atau orang gila melakukan pembunuhan terhadap seseorang?',
    options: [
      { id: 'a', text: 'Anak kecil tersebut wajib dihukum mati qishash' },
      { id: 'b', text: 'Tindakannya dikategorikan sebagai Pembunuhan Tersalah (Khatha\'), tidak ada qishash bagi keduanya, dan diyat dibebankan kepada \'aqilah mereka' },
      { id: 'c', text: 'Orang tua anak tersebut yang wajib diqishash mati' },
      { id: 'd', text: 'Tidak ada konsekuensi hukum dan diyat sama sekali' },
      { id: 'e', text: 'Anak tersebut dipenjara hingga berusia 50 tahun' },
    ],
    correctOptionId: 'b',
    explanation: 'Kaidah fiqih menetapkan: "Amadush shabiyyi wal majnun khatha\'un" (Kesengajaan anak kecil dan orang gila terhitung sebagai perbuatan tersalah/khatha\'). Mereka terbebas dari qishash karena pena hukum diangkat dari mereka, namun diyat tetap wajib ditanggung \'aqilah.',
    dalil: 'HR. Abu Dawud no. 4403 & Tirmidzi no. 1423: "Diangkat pena dari tiga golongan..."',
  },
  {
    id: 'jn_25',
    question: 'Manakah ayat Al-Qur\'an yang menganjurkan para wali korban pembunuhan untuk memaafkan pelaku sebagai amalan sedekah yang menghapuskan dosa?',
    options: [
      { id: 'a', text: '"Dan barangsiapa melepaskan haknya (qishash) sebagai sedekah, maka itu menjadi penebus dosa baginya" (Faman tashaddaqa bihi fahuwa kaffāratul lah)' },
      { id: 'b', text: '"Dan janganlah kamu membunuh jiwa yang diharamkan Allah kecuali dengan hak"' },
      { id: 'c', text: '"Sesungguhnya orang-orang mukmin itu bersaudara"' },
      { id: 'd', text: '"Tiap-tiap yang berjiwa akan merasakan mati"' },
      { id: 'e', text: '"Dan janganlah kamu berbuat kerusakan di muka bumi"' },
    ],
    correctOptionId: 'a',
    explanation: 'Al-Qur\'an memuji sikap pemaafan wali korban yang menggugurkan hak qishash atau diyat demi mengharap ridha Allah sebagai kaffarah (penghapus dosa) bagi dirinya.',
    dalil: 'QS. Al-Ma\'idah: 45: "Barangsiapa melepaskan hak qishashnya, maka itu menjadi penebus dosa baginya."',
  },
];

const content = `import { JinayatQuizQuestion } from '../../types/jinayat';

export const JINAYAT_QUIZ: JinayatQuizQuestion[] = ${JSON.stringify(jinayatQuestions, null, 2)};
`;

fs.writeFileSync('src/data/quizzes/jinayatQuizData.ts', content, 'utf8');
console.log('Successfully generated src/data/quizzes/jinayatQuizData.ts with 25 questions');
